# Generated by Django 6.1.1 on 2026-09-10 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('DosageId', models.AutoField(primary_key=True, serialize=False)),
                ('DosageValue', models.CharField(choices=[('250mg', '250mg'), ('500mg', '500mg'), ('650mg', '650mg'), ('1000mg', '1000mg'), ('5ml', '5ml'), ('10ml', '10ml'), ('1 tablet', '1 tablet')], max_length=50)),
                ('Instructions', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MasterMedicine',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(db_index=True, max_length=200)),
                ('Manufacturer', models.CharField(max_length=200)),
                ('GenericName', models.CharField(blank=True, max_length=200)),
                ('Category', models.CharField(blank=True, max_length=100)),
                ('CostValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
                ('BloodGroup', models.CharField(max_length=10)),
                ('Weight', models.FloatField()),
                ('Height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentStatus', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('AppointmentDateTime', models.DateTimeField()),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('ConsultationId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationStatus', models.CharField(choices=[('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Ongoing', 'Ongoing')], default='Waiting', max_length=20)),
                ('Diagnosis', models.CharField(max_length=100)),
                ('Symptoms', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=200)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='DoctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('LabtestId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=100)),
                ('NormalName', models.CharField(max_length=100)),
                ('TestCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DepartmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='apibackendapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='LabPrescription',
            fields=[
                ('LabPrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('Sample collected', 'Sample collected'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=20)),
                ('SampleType', models.CharField(max_length=100)),
                ('LabTestDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ConsultationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apibackendapp.consultation')),
                ('DoctorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_prescription', to='apibackendapp.doctor')),
                ('LabTestId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_prescriptions', to='apibackendapp.labtest')),
                ('PatientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_prescriptions', to='apibackendapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('BillDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BillStatus', models.CharField(max_length=50)),
                ('BillType', models.CharField(max_length=50)),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='PatientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('PaymentDate', models.DateField()),
                ('PaymentStatus', models.CharField(max_length=50)),
                ('BillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.bill')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('BillDate', models.DateField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBillItem',
            fields=[
                ('BillItemId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LineAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apibackendapp.pharmacybill')),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.mastermedicine')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('StockId', models.AutoField(primary_key=True, serialize=False)),
                ('QuantityOnHand', models.IntegerField(default=0)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReorderLevel', models.IntegerField(default=10)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='apibackendapp.mastermedicine')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('PrescriptionDateTime', models.DateTimeField()),
                ('Status', models.CharField(choices=[('Dispensed', 'Dispensed'), ('Not Dispensed', 'Not Dispensed'), ('Partially Dispensed', 'Partially Dispensed')], default='Not Dispensed', max_length=30)),
                ('ConsultationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.consultation')),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='Prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.prescription'),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('PrescriptionItemId', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.CharField(max_length=30)),
                ('Frequency', models.CharField(max_length=30)),
                ('DosageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.dosage')),
                ('MedicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.mastermedicine')),
                ('PrescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DateofBirth', models.DateField()),
                ('DateOfJoining', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacybill',
            name='DispensedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.staff'),
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('ReportId', models.AutoField(primary_key=True, serialize=False)),
                ('ReportDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ActualReading', models.TextField()),
                ('remarks', models.TextField()),
                ('LabPrescriptionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='apibackendapp.labprescription')),
                ('LabTechnician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='apibackendapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('AuditId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionType', models.CharField(max_length=100)),
                ('TableAffected', models.CharField(max_length=100)),
                ('RecordId', models.IntegerField(null=True)),
                ('Details', models.TextField(blank=True, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('StaffId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='apibackendapp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='ReceptionistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='apibackendapp.staff'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('TokenNo', models.AutoField(primary_key=True, serialize=False)),
                ('TokenDate', models.DateTimeField()),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.appointment')),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.doctor')),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='apibackendapp.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='apibackendapp.user'),
        ),
    ]
