# Generated by Django 6.1.1 on 2026-09-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labprescription',
            name='ConsultationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='apibackendapp.consultation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='ConsultationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='apibackendapp.consultation'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='PrescriptionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apibackendapp.prescription'),
        ),
    ]
