# Generated by Django 6.1.1 on 2026-09-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0003_auditlog_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mastermedicine',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
